### ISSUE TITLE
tasks with QTableWidget

### ISSUE THREAD

**Issue by Nbdyleto** [Nbdyleto/pyqt5_json-daily-task#1]
QTableWidget. Requisites.

- [ ] show name headers;
- [x] load all data in QTable;
- [ ] load just data in QTable from selected date (with no permission to edit);
- [ ]  add a task in real time execution;
   - [ ] in simultaneous, add that task in json;
- [ ] allow change data in QTable;
   - [ ] in simultaneous, change, in same position, the respective data in json;
   - [ ] allow check tasks.
- [ ] change color of task_type cell to the respective task_type color.

**Comment by Nbdyleto** [comment]
```
def change_data(self, item):
        row, col = item.row(), item.column()
        print(f'new data: {item.text()} at pos {row, col}')
        task_id = (widgets.tableWidget.item(row, 0)).text()

        . . .

        for index, result in enumerate(results['lists']):
            items = result[first_keys[index]] # items receive all items from specific list_key.
            widgets.tableWidget.setRowCount(15) # [ ] Set a valid row count...
            for it in items:
                if it['task_id'] == int(task_id):
                    pass
```

in 'pass' add some tasks.py function which update task data by _task_id_ and respective field _(col)_

**Comment by Nbdyleto** [comment]
- add a task in real time execution;
- in simultaneous, add that task in json;

new code, deleting redundancies and useless code. Pass the read logic to tasks.py based on values send by change_data of main.py.

### main.py
```
def change_data(self, item):
        row, col = item.row(), item.column()
        new_data = item.text()
        print(f'new data: {item.text()} at pos {row, col}')
        
        topic_id = 0
        if (widgets.tableWidget.item(row, 1) == 'Math'):
            topic_id = 0
        elif (widgets.tableWidget.item(row, 1) == 'Geo'):
            topic_id = 1
            
        task_id = (widgets.tableWidget.item(row, 0)).text()
        new_data = (widgets.tableWidget.item(row, col)).text()

        self.main.change_data(topic_id, task_id, new_data)
```

### tasks.py
```
def change_data(self, topic_id, task_id, new_data):
        
        topic_list = self.instance_list[topic_id].serialize()
        for index, task in enumerate(topic_list['Math']):
            if str(task['task_id']) == task_id:
                print(f'Old task: {self.instance_list[topic_id].task_list[index].serialize()}')
                self.instance_list[topic_id].task_list[index].name = new_data
                print(f'New task: {self.instance_list[topic_id].task_list[index].serialize()}')

        self.update_json()
```

- [ ] this code change always the _name_ attribute of instance, never the correct and respective attribute. find a logic to change that.
- [ ] make code more intuitive and elegant.

**Comment by Nbdyleto** [comment]
closing the logic with json. Migrating to MySql; pratical and more simple for work with instances!
:(
